version: '3.5'

networks:
  chatbot-front-tier:
    name: ft-chatbot-net

services:
  react-chatbot:
    hostname: localhost
    image: react-chatbot:1.0
    build:
      context: .
    container_name: react-chatbot
    expose:
      - 80
    ports:
      - 8080:80
    restart: always
    networks:
      - chatbot-front-tier
