version: '3.6'

services:
  db:
    hostname: postgres-chatbot
    image: postgres:11
    container_name: chatbot-postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatbot
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=masterkey
